# -*- coding: utf-8 -*-
"""extractor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eW54Y7a1ynFFz72Hbuvk8DXJQsj8NF8j
"""

import yfinance as yf
import datetime
import numpy as np
import pandas as pd

class Portfolio:

    def __init__(self, assets: dict, start="2020-01-01", end=datetime.datetime.now().strftime("%Y-%m-%d")):
        self.assets = assets
        self.start = start
        self.end = end
        self.prices = self._download_prices()

    def _download_prices(self):
        prices = yf.download( list(self.assets.keys()), start=self.start, end=self.end)['Adj Close']
        prices.to_excel('Data.xlsx')
        return prices.dropna()

     
#création du ptf
df = pd.read_excel ('PTF.xlsx')
new_df = df[["Tickers", "Qté"]]
list_tickers = new_df["Tickers"].to_list()
list_qte = new_df["Qté"].to_list()
ptf = {}
for i in range(len(list_tickers)):
    ptf[list_tickers[i]] = list_qte[i]

#instanciation
if __name__ == "__main__":
 	Ptf= Portfolio(ptf,start='2018-12-01')
	Ptf._download_prices()

